### ISSUE TITLE
READMEのGPIO22

### ISSUE THREAD

**Issue by rn10** [Akkiesoft/akkiesoft-pico#1]
ドキュメントの最初にあるGPIO22はGPIO27ではないでしょうか？

**Comment by Akkiesoft** [comment]
どのプロジェクトのREADMEになりますでしょうか。
モノが多いのと、ルートディレクトリのREADMEには実質何も書いていないので…

**Comment by Akkiesoft** [comment]
見つけました。こちらですね。
https://github.com/Akkiesoft/akkiesoft-pico/tree/main/CircuitPython/keybow-for-rp2040

先にでてきたGPIO22はGPIO27であっています。修正します。
